apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: kharatramesh/vadapavimages:php-database
        name: php-database
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123"
