apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-db
  name: mongo-db1
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongo-db1
  type: ClusterIP
